name: xfathub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  supabase_flutter: ^2.12.1
  flutter_dotenv: ^6.0.0
  permission_handler: ^12.0.1
  pedometer: ^4.2.0
  flutter_background_service: ^5.0.10
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.20.2
  connectivity_plus: ^7.0.0
  workmanager: ^0.9.0+3
  geolocator: ^11.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  uuid: ^4.5.3
  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - .env
  uses-material-design: true
