-- Add missing profile columns
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS age INT,
ADD COLUMN IF NOT EXISTS current_weight DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS initial_weight DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS height DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS step_goal INT,
ADD COLUMN IF NOT EXISTS hydration_goal DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS profile_completed BOOLEAN DEFAULT false;
