-- Create hydration_goals table
CREATE TABLE IF NOT EXISTS hydration_goals (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  goal_ml INTEGER NOT NULL DEFAULT 2000,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(user_id)
);

-- Create hydration_daily table for synced records
CREATE TABLE IF NOT EXISTS hydration_daily (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  time TEXT NOT NULL,
  amount_ml INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(user_id, date, time)
);

-- Create step_tracker_goals table
CREATE TABLE IF NOT EXISTS step_tracker_goals (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  goal_steps INTEGER NOT NULL DEFAULT 10000,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(user_id)
);

-- Create step_tracker_daily table for synced records
CREATE TABLE IF NOT EXISTS step_tracker_daily (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  steps INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(user_id, date)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS hydration_goals_user_id_idx ON hydration_goals(user_id);
CREATE INDEX IF NOT EXISTS hydration_daily_user_id_idx ON hydration_daily(user_id);
CREATE INDEX IF NOT EXISTS hydration_daily_date_idx ON hydration_daily(date);
CREATE INDEX IF NOT EXISTS step_tracker_goals_user_id_idx ON step_tracker_goals(user_id);
CREATE INDEX IF NOT EXISTS step_tracker_daily_user_id_idx ON step_tracker_daily(user_id);
CREATE INDEX IF NOT EXISTS step_tracker_daily_date_idx ON step_tracker_daily(date);

-- Enable RLS (Row Level Security)
ALTER TABLE hydration_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE hydration_daily ENABLE ROW LEVEL SECURITY;
ALTER TABLE step_tracker_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE step_tracker_daily ENABLE ROW LEVEL SECURITY;

-- Create policies for hydration_goals
CREATE POLICY "Users can view their own hydration goal" ON hydration_goals
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own hydration goal" ON hydration_goals
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own hydration goal" ON hydration_goals
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Create policies for hydration_daily
CREATE POLICY "Users can view their own hydration records" ON hydration_daily
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own hydration records" ON hydration_daily
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own hydration records" ON hydration_daily
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own hydration records" ON hydration_daily
  FOR DELETE USING (auth.uid() = user_id);

-- Create policies for step_tracker_goals
CREATE POLICY "Users can view their own step goal" ON step_tracker_goals
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own step goal" ON step_tracker_goals
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own step goal" ON step_tracker_goals
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Create policies for step_tracker_daily
CREATE POLICY "Users can view their own step records" ON step_tracker_daily
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own step records" ON step_tracker_daily
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own step records" ON step_tracker_daily
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own step records" ON step_tracker_daily
  FOR DELETE USING (auth.uid() = user_id);
