-- Booking credit system migration aligned with UUID schema in booking.sql

-- Ensure package fields required for Stripe checkout and credit expiry exist.
ALTER TABLE IF EXISTS public.packages
  ADD COLUMN IF NOT EXISTS stripe_price_id TEXT,
  ADD COLUMN IF NOT EXISTS validity_days INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS allowed_class_names TEXT[] NOT NULL DEFAULT '{}';

-- Ensure booking payload columns used by Flutter model exist.
ALTER TABLE IF EXISTS public.bookings
  ADD COLUMN IF NOT EXISTS qr_code_data TEXT,
  ADD COLUMN IF NOT EXISTS receipt_url TEXT;

-- Credit wallet per user/package.
CREATE TABLE IF NOT EXISTS public.user_subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  package_id UUID NOT NULL REFERENCES public.packages(id) ON DELETE CASCADE,
  sessions_remaining INTEGER NOT NULL DEFAULT 0,
  expiry_date DATE NOT NULL,
  last_payment_intent_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT user_subscriptions_sessions_non_negative CHECK (sessions_remaining >= 0),
  CONSTRAINT user_subscriptions_unique_user_package UNIQUE (user_id, package_id)
);

-- Webhook idempotency ledger.
CREATE TABLE IF NOT EXISTS public.stripe_webhook_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stripe_event_id TEXT NOT NULL UNIQUE,
  event_type TEXT NOT NULL,
  payload JSONB NOT NULL,
  processed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Safety constraints for slots and bookings.
ALTER TABLE IF EXISTS public.gym_slots
  DROP CONSTRAINT IF EXISTS gym_slots_capacity_bounds;

ALTER TABLE IF EXISTS public.gym_slots
  ADD CONSTRAINT gym_slots_capacity_bounds
  CHECK (occupied_spots >= 0 AND occupied_spots <= total_spots);

CREATE UNIQUE INDEX IF NOT EXISTS bookings_user_slot_active_idx
  ON public.bookings(user_id, slot_id)
  WHERE slot_id IS NOT NULL AND status <> 'cancelled';

CREATE INDEX IF NOT EXISTS user_subscriptions_user_expiry_idx
  ON public.user_subscriptions(user_id, expiry_date DESC);

CREATE INDEX IF NOT EXISTS bookings_user_status_idx
  ON public.bookings(user_id, status);

CREATE INDEX IF NOT EXISTS gym_slots_time_idx
  ON public.gym_slots(start_time);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_user_subscriptions_updated_at ON public.user_subscriptions;
CREATE TRIGGER set_user_subscriptions_updated_at
BEFORE UPDATE ON public.user_subscriptions
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.user_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own subscriptions" ON public.user_subscriptions;
CREATE POLICY "Users can view their own subscriptions"
  ON public.user_subscriptions
  FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view their own bookings" ON public.bookings;
CREATE POLICY "Users can view their own bookings"
  ON public.bookings
  FOR SELECT
  USING (auth.uid() = user_id);

DROP FUNCTION IF EXISTS public.get_user_credit_balance(UUID, UUID);
CREATE OR REPLACE FUNCTION public.get_user_credit_balance(
  p_user_id UUID,
  p_package_id UUID DEFAULT NULL
)
RETURNS JSONB
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT
    CASE
      WHEN auth.uid() IS NULL OR auth.uid() <> p_user_id THEN
        jsonb_build_object('success', false, 'error', 'unauthorized')
      WHEN p_package_id IS NULL THEN
        COALESCE(
          (
            SELECT jsonb_build_object(
              'success', true,
              'sessions_remaining', COALESCE(SUM(sessions_remaining), 0),
              'active_subscriptions', COUNT(*) FILTER (WHERE expiry_date >= CURRENT_DATE),
              'next_expiry_date', MIN(expiry_date) FILTER (WHERE expiry_date >= CURRENT_DATE)
            )
            FROM public.user_subscriptions
            WHERE user_id = p_user_id
              AND expiry_date >= CURRENT_DATE
          ),
          jsonb_build_object(
            'success', true,
            'sessions_remaining', 0,
            'active_subscriptions', 0,
            'next_expiry_date', NULL
          )
        )
      ELSE
        COALESCE(
          (
            SELECT jsonb_build_object(
              'success', true,
              'sessions_remaining', COALESCE(SUM(sessions_remaining), 0),
              'active_subscriptions', COUNT(*) FILTER (WHERE expiry_date >= CURRENT_DATE),
              'next_expiry_date', MIN(expiry_date) FILTER (WHERE expiry_date >= CURRENT_DATE)
            )
            FROM public.user_subscriptions
            WHERE user_id = p_user_id
              AND package_id = p_package_id
              AND expiry_date >= CURRENT_DATE
          ),
          jsonb_build_object(
            'success', true,
            'sessions_remaining', 0,
            'active_subscriptions', 0,
            'next_expiry_date', NULL
          )
        )
    END;
$$;

DROP FUNCTION IF EXISTS public.create_booking_with_credit(UUID, UUID, UUID);
CREATE OR REPLACE FUNCTION public.create_booking_with_credit(
  p_user_id UUID,
  p_slot_id UUID,
  p_package_id UUID
)
RETURNS JSONB
LANGUAGE sql
SECURITY DEFINER
AS $$
  WITH auth_check AS (
    SELECT auth.uid() IS NOT NULL AND auth.uid() = p_user_id AS ok
  ),
  subscription AS (
    SELECT us.id, us.package_id, p.allowed_class_names
    FROM public.user_subscriptions us
    JOIN public.packages p ON p.id = us.package_id
    WHERE us.user_id = p_user_id
      AND us.package_id = p_package_id
      AND us.expiry_date >= CURRENT_DATE
      AND us.sessions_remaining > 0
    ORDER BY us.expiry_date DESC
    LIMIT 1
    FOR UPDATE
  ),
  slot_state AS (
    SELECT gs.id, gs.total_spots, gs.occupied_spots, gs.class_name
    FROM public.gym_slots gs
    WHERE gs.id = p_slot_id
    FOR UPDATE
  ),
  duplicate_booking AS (
    SELECT 1
    FROM public.bookings b
    WHERE b.user_id = p_user_id
      AND b.slot_id = p_slot_id
      AND b.status <> 'cancelled'
    LIMIT 1
  ),
  inserted AS (
    INSERT INTO public.bookings (
      user_id,
      package_id,
      slot_id,
      status,
      booking_date,
      total_paid,
      session_number,
      qr_code_data
    )
    SELECT
      p_user_id,
      p_package_id,
      p_slot_id,
      'upcoming',
      now(),
      0,
      1,
      ''
    FROM auth_check a
    WHERE a.ok
      AND EXISTS (SELECT 1 FROM subscription)
      AND EXISTS (SELECT 1 FROM slot_state WHERE occupied_spots < total_spots)
      AND (
        EXISTS (
          SELECT 1
          FROM subscription s
          JOIN slot_state ss ON true
          WHERE COALESCE(array_length(s.allowed_class_names, 1), 0) = 0
             OR ss.class_name = ANY(s.allowed_class_names)
        )
      )
      AND NOT EXISTS (SELECT 1 FROM duplicate_booking)
    RETURNING id
  ),
  decremented_subscription AS (
    UPDATE public.user_subscriptions us
    SET sessions_remaining = us.sessions_remaining - 1
    WHERE us.id = (SELECT id FROM subscription)
      AND EXISTS (SELECT 1 FROM inserted)
    RETURNING 1
  ),
  incremented_slot AS (
    UPDATE public.gym_slots gs
    SET occupied_spots = gs.occupied_spots + 1
    WHERE gs.id = p_slot_id
      AND EXISTS (SELECT 1 FROM inserted)
    RETURNING 1
  ),
  updated_booking AS (
    UPDATE public.bookings b
    SET qr_code_data = jsonb_build_object(
      'booking_id', b.id,
      'user_id', p_user_id,
      'slot_id', p_slot_id,
      'package_id', p_package_id
    )::TEXT
    FROM inserted i
    WHERE b.id = i.id
    RETURNING b.*
  )
  SELECT CASE
    WHEN NOT EXISTS (SELECT 1 FROM auth_check WHERE ok) THEN
      jsonb_build_object('success', false, 'error', 'unauthorized')
    WHEN NOT EXISTS (SELECT 1 FROM subscription) THEN
      jsonb_build_object('success', false, 'error', 'No sessions remaining. Please purchase a package.')
    WHEN NOT EXISTS (SELECT 1 FROM slot_state) THEN
      jsonb_build_object('success', false, 'error', 'Selected slot not found.')
    WHEN EXISTS (SELECT 1 FROM slot_state WHERE occupied_spots >= total_spots) THEN
      jsonb_build_object('success', false, 'error', 'Selected slot is already full.')
    WHEN EXISTS (
      SELECT 1
      FROM subscription s
      JOIN slot_state ss ON true
      WHERE COALESCE(array_length(s.allowed_class_names, 1), 0) > 0
        AND ss.class_name <> ALL(s.allowed_class_names)
    ) THEN
      jsonb_build_object('success', false, 'error', 'This slot is not available for the selected package.')
    WHEN EXISTS (SELECT 1 FROM duplicate_booking) THEN
      jsonb_build_object('success', false, 'error', 'You already booked this slot.')
    WHEN NOT EXISTS (SELECT 1 FROM inserted) THEN
      jsonb_build_object('success', false, 'error', 'Unable to create booking.')
    ELSE
      jsonb_build_object('success', true, 'booking', (SELECT to_jsonb(ub) FROM updated_booking ub LIMIT 1))
  END;
$$;

DROP FUNCTION IF EXISTS public.cancel_booking_with_refund(UUID, UUID);
CREATE OR REPLACE FUNCTION public.cancel_booking_with_refund(
  p_booking_id UUID,
  p_user_id UUID
)
RETURNS JSONB
LANGUAGE sql
SECURITY DEFINER
AS $$
  WITH auth_check AS (
    SELECT auth.uid() IS NOT NULL AND auth.uid() = p_user_id AS ok
  ),
  booking_row AS (
    SELECT b.id, b.package_id, b.slot_id, b.status
    FROM public.bookings b
    WHERE b.id = p_booking_id
      AND b.user_id = p_user_id
    FOR UPDATE
  ),
  updated_booking AS (
    UPDATE public.bookings b
    SET status = 'cancelled'
    WHERE b.id = p_booking_id
      AND EXISTS (SELECT 1 FROM auth_check WHERE ok)
      AND EXISTS (SELECT 1 FROM booking_row WHERE status = 'upcoming')
    RETURNING 1
  ),
  updated_subscription AS (
    UPDATE public.user_subscriptions us
    SET sessions_remaining = us.sessions_remaining + 1
    WHERE us.id = (
      SELECT us2.id
      FROM public.user_subscriptions us2
      WHERE us2.user_id = p_user_id
        AND us2.package_id = (SELECT br.package_id FROM booking_row br LIMIT 1)
      ORDER BY us2.expiry_date DESC
      LIMIT 1
    )
      AND EXISTS (SELECT 1 FROM updated_booking)
    RETURNING 1
  ),
  updated_slot AS (
    UPDATE public.gym_slots gs
    SET occupied_spots = GREATEST(gs.occupied_spots - 1, 0)
    WHERE gs.id = (SELECT br.slot_id FROM booking_row br LIMIT 1)
      AND (SELECT br.slot_id FROM booking_row br LIMIT 1) IS NOT NULL
      AND EXISTS (SELECT 1 FROM updated_booking)
    RETURNING 1
  )
  SELECT CASE
    WHEN NOT EXISTS (SELECT 1 FROM auth_check WHERE ok) THEN
      jsonb_build_object('success', false, 'error', 'unauthorized')
    WHEN NOT EXISTS (SELECT 1 FROM booking_row) THEN
      jsonb_build_object('success', false, 'error', 'Booking not found.')
    WHEN EXISTS (SELECT 1 FROM booking_row WHERE status = 'cancelled') THEN
      jsonb_build_object('success', false, 'error', 'Booking already cancelled.')
    WHEN EXISTS (SELECT 1 FROM booking_row WHERE status <> 'upcoming') THEN
      jsonb_build_object('success', false, 'error', 'Only upcoming bookings can be cancelled.')
    WHEN NOT EXISTS (SELECT 1 FROM updated_booking) THEN
      jsonb_build_object('success', false, 'error', 'Unable to cancel booking.')
    ELSE
      jsonb_build_object('success', true)
  END;
$$;

DROP FUNCTION IF EXISTS public.reschedule_booking(UUID, UUID, UUID);
CREATE OR REPLACE FUNCTION public.reschedule_booking(
  p_booking_id UUID,
  p_user_id UUID,
  p_new_slot_id UUID
)
RETURNS JSONB
LANGUAGE sql
SECURITY DEFINER
AS $$
  WITH auth_check AS (
    SELECT auth.uid() IS NOT NULL AND auth.uid() = p_user_id AS ok
  ),
  booking_row AS (
    SELECT b.id, b.slot_id, b.status
    FROM public.bookings b
    WHERE b.id = p_booking_id
      AND b.user_id = p_user_id
    FOR UPDATE
  ),
  new_slot AS (
    SELECT gs.id, gs.total_spots, gs.occupied_spots
    FROM public.gym_slots gs
    WHERE gs.id = p_new_slot_id
    FOR UPDATE
  ),
  updated_booking AS (
    UPDATE public.bookings b
    SET slot_id = p_new_slot_id
    WHERE b.id = p_booking_id
      AND EXISTS (SELECT 1 FROM auth_check WHERE ok)
      AND EXISTS (SELECT 1 FROM booking_row WHERE status = 'upcoming')
      AND EXISTS (SELECT 1 FROM new_slot WHERE occupied_spots < total_spots)
      AND EXISTS (SELECT 1 FROM booking_row WHERE slot_id IS DISTINCT FROM p_new_slot_id)
    RETURNING 1
  ),
  old_slot_update AS (
    UPDATE public.gym_slots gs
    SET occupied_spots = GREATEST(gs.occupied_spots - 1, 0)
    WHERE gs.id = (SELECT br.slot_id FROM booking_row br LIMIT 1)
      AND EXISTS (SELECT 1 FROM updated_booking)
      AND (SELECT br.slot_id FROM booking_row br LIMIT 1) IS NOT NULL
    RETURNING 1
  ),
  new_slot_update AS (
    UPDATE public.gym_slots gs
    SET occupied_spots = gs.occupied_spots + 1
    WHERE gs.id = p_new_slot_id
      AND EXISTS (SELECT 1 FROM updated_booking)
    RETURNING 1
  )
  SELECT CASE
    WHEN NOT EXISTS (SELECT 1 FROM auth_check WHERE ok) THEN
      jsonb_build_object('success', false, 'error', 'unauthorized')
    WHEN NOT EXISTS (SELECT 1 FROM booking_row) THEN
      jsonb_build_object('success', false, 'error', 'Booking not found.')
    WHEN EXISTS (SELECT 1 FROM booking_row WHERE status <> 'upcoming') THEN
      jsonb_build_object('success', false, 'error', 'Only upcoming bookings can be rescheduled.')
    WHEN EXISTS (SELECT 1 FROM booking_row WHERE slot_id = p_new_slot_id) THEN
      jsonb_build_object('success', false, 'error', 'Please choose a different slot.')
    WHEN NOT EXISTS (SELECT 1 FROM new_slot) THEN
      jsonb_build_object('success', false, 'error', 'New slot not found.')
    WHEN EXISTS (SELECT 1 FROM new_slot WHERE occupied_spots >= total_spots) THEN
      jsonb_build_object('success', false, 'error', 'New slot is already full.')
    WHEN NOT EXISTS (SELECT 1 FROM updated_booking) THEN
      jsonb_build_object('success', false, 'error', 'Unable to reschedule booking.')
    ELSE
      jsonb_build_object('success', true)
  END;
$$;

GRANT EXECUTE ON FUNCTION public.get_user_credit_balance(UUID, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_booking_with_credit(UUID, UUID, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cancel_booking_with_refund(UUID, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reschedule_booking(UUID, UUID, UUID) TO authenticated;
