-- Consolidated init schema.
-- Tables first, then RLS, then policies, then functions, indexes, grants, storage.
-- Seed / dummy data intentionally excluded.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Core identity tables
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT UNIQUE NOT NULL,
  name TEXT,
  bio TEXT,
  profile_picture_url TEXT,
  gender TEXT,
  birthdate DATE,
  age INT,
  current_weight DOUBLE PRECISION,
  initial_weight DOUBLE PRECISION,
  weight_goal DOUBLE PRECISION,
  height DOUBLE PRECISION,
  step_goal INT,
  hydration_goal INTEGER,
  profile_completed BOOLEAN DEFAULT false,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS weight_history (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  weight DOUBLE PRECISION NOT NULL,
  recorded_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Booking tables
CREATE TABLE IF NOT EXISTS packages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  sessions_count INTEGER NOT NULL,
  category TEXT NOT NULL DEFAULT 'Gym',
  badge TEXT,
  is_featured BOOLEAN NOT NULL DEFAULT FALSE,
  icon_name TEXT NOT NULL DEFAULT 'fitness_center',
  stripe_price_id TEXT,
  validity_days INTEGER NOT NULL DEFAULT 30,
  allowed_class_names TEXT[] NOT NULL DEFAULT '{}',
  benefits TEXT[] NOT NULL DEFAULT '{}',
  rules TEXT[] NOT NULL DEFAULT '{}',
  gym_names TEXT[] NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS gyms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  venue TEXT,
  address TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT gyms_status_check CHECK (status = ANY (ARRAY['active', 'inactive']))
);

CREATE TABLE IF NOT EXISTS package_gyms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  package_id UUID NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
  gym_id UUID NOT NULL REFERENCES gyms(id) ON DELETE CASCADE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT package_gyms_unique_package_gym UNIQUE (package_id, gym_id)
);

CREATE TABLE IF NOT EXISTS gym_slots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  gym_id UUID NOT NULL REFERENCES gyms(id) ON DELETE CASCADE,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  class_name TEXT NOT NULL,
  coach_name TEXT,
  location TEXT,
  total_spots INTEGER NOT NULL DEFAULT 20,
  occupied_spots INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT gym_slots_time_check CHECK (end_time > start_time),
  CONSTRAINT gym_slots_capacity_check CHECK (occupied_spots >= 0 AND occupied_spots <= total_spots)
);

CREATE TABLE IF NOT EXISTS bookings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  package_id UUID REFERENCES packages(id),
  slot_id UUID REFERENCES gym_slots(id),
  booking_date TIMESTAMPTZ NOT NULL DEFAULT now(),
  status TEXT NOT NULL DEFAULT 'upcoming',
  total_paid NUMERIC,
  receipt_url TEXT,
  qr_code_data TEXT,
  session_number INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT bookings_status_check CHECK (
    status = ANY (
      ARRAY[
        'upcoming'::TEXT,
        'missed'::TEXT,
        'completed'::TEXT
      ]
    )
  )
);

CREATE TABLE IF NOT EXISTS user_subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  package_id UUID NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
  sessions_remaining INTEGER NOT NULL DEFAULT 0,
  expiry_date DATE NOT NULL,
  last_payment_intent_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT user_subscriptions_sessions_non_negative CHECK (sessions_remaining >= 0),
  CONSTRAINT user_subscriptions_unique_user_package UNIQUE (user_id, package_id)
);

CREATE TABLE IF NOT EXISTS stripe_webhook_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stripe_event_id TEXT NOT NULL UNIQUE,
  event_type TEXT NOT NULL,
  payload JSONB NOT NULL,
  processed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Community tables
CREATE TABLE IF NOT EXISTS posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  media_url TEXT,
  location_name TEXT,
  location_lat DOUBLE PRECISION,
  location_lng DOUBLE PRECISION,
  activity_id TEXT,
  activity_type TEXT,
  activity_title TEXT,
  activity_duration_seconds INTEGER,
  activity_distance DOUBLE PRECISION,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS post_comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id UUID NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS post_likes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  post_id UUID NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(post_id, user_id)
);

CREATE TABLE IF NOT EXISTS post_favourites (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  post_id UUID NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(post_id, user_id)
);

CREATE TABLE IF NOT EXISTS user_followers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  follower_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  following_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(follower_id, following_id)
);

-- Tracker tables
CREATE TABLE IF NOT EXISTS hydration_goals (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  goal_ml INTEGER NOT NULL DEFAULT 2000,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(user_id)
);

CREATE TABLE IF NOT EXISTS hydration_daily (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  time TEXT NOT NULL,
  amount_ml INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(user_id, date, time)
);

CREATE TABLE IF NOT EXISTS step_tracker_goals (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  goal_steps INTEGER NOT NULL DEFAULT 10000,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(user_id)
);

CREATE TABLE IF NOT EXISTS step_tracker_daily (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  steps INTEGER NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(user_id, date)
);

-- RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE weight_history ENABLE ROW LEVEL SECURITY;

ALTER TABLE packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE gyms ENABLE ROW LEVEL SECURITY;
ALTER TABLE package_gyms ENABLE ROW LEVEL SECURITY;
ALTER TABLE gym_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE stripe_webhook_events ENABLE ROW LEVEL SECURITY;

ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_favourites ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_followers ENABLE ROW LEVEL SECURITY;

ALTER TABLE hydration_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE hydration_daily ENABLE ROW LEVEL SECURITY;
ALTER TABLE step_tracker_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE step_tracker_daily ENABLE ROW LEVEL SECURITY;

-- Policies: profiles
DROP POLICY IF EXISTS "Users can view their own profile" ON profiles;
CREATE POLICY "Users can view their own profile" ON profiles
  FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update their own profile" ON profiles;
CREATE POLICY "Users can update their own profile" ON profiles
  FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can insert their own profile" ON profiles;
CREATE POLICY "Users can insert their own profile" ON profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can view their own weight history" ON weight_history;
CREATE POLICY "Users can view their own weight history" ON weight_history
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own weight history" ON weight_history;
CREATE POLICY "Users can insert their own weight history" ON weight_history
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Policies: booking
DROP POLICY IF EXISTS "Users can view their own subscriptions" ON user_subscriptions;
CREATE POLICY "Users can view their own subscriptions"
  ON user_subscriptions
  FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view their own bookings" ON bookings;
CREATE POLICY "Users can view their own bookings"
  ON bookings
  FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can create bookings" ON bookings;
CREATE POLICY "Users can create bookings"
  ON bookings
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own bookings" ON bookings;
CREATE POLICY "Users can update their own bookings"
  ON bookings
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own bookings" ON bookings;
CREATE POLICY "Users can delete their own bookings"
  ON bookings
  FOR DELETE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Anyone can view packages" ON packages;
CREATE POLICY "Anyone can view packages"
  ON packages
  FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Anyone can view gyms" ON gyms;
CREATE POLICY "Anyone can view gyms"
  ON gyms
  FOR SELECT
  USING (status = 'active');

DROP POLICY IF EXISTS "Anyone can view package gyms" ON package_gyms;
CREATE POLICY "Anyone can view package gyms"
  ON package_gyms
  FOR SELECT
  USING (is_active = TRUE);

DROP POLICY IF EXISTS "Anyone can view gym slots" ON gym_slots;
CREATE POLICY "Anyone can view gym slots"
  ON gym_slots
  FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Service role can manage webhook events" ON stripe_webhook_events;
CREATE POLICY "Service role can manage webhook events"
  ON stripe_webhook_events
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Policies: community
DROP POLICY IF EXISTS "Anyone can view posts" ON posts;
CREATE POLICY "Anyone can view posts" ON posts FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own posts" ON posts;
CREATE POLICY "Users can insert their own posts" ON posts FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own posts" ON posts;
CREATE POLICY "Users can update their own posts" ON posts FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own posts" ON posts;
CREATE POLICY "Users can delete their own posts" ON posts FOR DELETE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Anyone can view comments" ON post_comments;
CREATE POLICY "Anyone can view comments" ON post_comments FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own comments" ON post_comments;
CREATE POLICY "Users can insert their own comments" ON post_comments FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Anyone can view likes" ON post_likes;
CREATE POLICY "Anyone can view likes" ON post_likes FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own likes" ON post_likes;
CREATE POLICY "Users can insert their own likes" ON post_likes FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own likes" ON post_likes;
CREATE POLICY "Users can delete their own likes" ON post_likes FOR DELETE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view their own favourites" ON post_favourites;
CREATE POLICY "Users can view their own favourites" ON post_favourites FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own favourites" ON post_favourites;
CREATE POLICY "Users can insert their own favourites" ON post_favourites FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own favourites" ON post_favourites;
CREATE POLICY "Users can delete their own favourites" ON post_favourites FOR DELETE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Anyone can view followers" ON user_followers;
CREATE POLICY "Anyone can view followers" ON user_followers FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can follow others" ON user_followers;
CREATE POLICY "Users can follow others" ON user_followers FOR INSERT WITH CHECK (auth.uid() = follower_id);

DROP POLICY IF EXISTS "Users can unfollow others" ON user_followers;
CREATE POLICY "Users can unfollow others" ON user_followers FOR DELETE USING (auth.uid() = follower_id);

-- Policies: tracker
DROP POLICY IF EXISTS "Users can view their own hydration goal" ON hydration_goals;
CREATE POLICY "Users can view their own hydration goal" ON hydration_goals
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own hydration goal" ON hydration_goals;
CREATE POLICY "Users can update their own hydration goal" ON hydration_goals
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own hydration goal" ON hydration_goals;
CREATE POLICY "Users can insert their own hydration goal" ON hydration_goals
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view their own hydration records" ON hydration_daily;
CREATE POLICY "Users can view their own hydration records" ON hydration_daily
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own hydration records" ON hydration_daily;
CREATE POLICY "Users can insert their own hydration records" ON hydration_daily
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own hydration records" ON hydration_daily;
CREATE POLICY "Users can update their own hydration records" ON hydration_daily
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own hydration records" ON hydration_daily;
CREATE POLICY "Users can delete their own hydration records" ON hydration_daily
  FOR DELETE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view their own step goal" ON step_tracker_goals;
CREATE POLICY "Users can view their own step goal" ON step_tracker_goals
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own step goal" ON step_tracker_goals;
CREATE POLICY "Users can update their own step goal" ON step_tracker_goals
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own step goal" ON step_tracker_goals;
CREATE POLICY "Users can insert their own step goal" ON step_tracker_goals
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view their own step records" ON step_tracker_daily;
CREATE POLICY "Users can view their own step records" ON step_tracker_daily
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own step records" ON step_tracker_daily;
CREATE POLICY "Users can insert their own step records" ON step_tracker_daily
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own step records" ON step_tracker_daily;
CREATE POLICY "Users can update their own step records" ON step_tracker_daily
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own step records" ON step_tracker_daily;
CREATE POLICY "Users can delete their own step records" ON step_tracker_daily
  FOR DELETE USING (auth.uid() = user_id);

-- Other objects: functions, triggers, indexes, grants, storage
CREATE INDEX IF NOT EXISTS package_gyms_package_idx ON package_gyms(package_id) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS package_gyms_gym_idx ON package_gyms(gym_id) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS gyms_status_idx ON gyms(status);
CREATE INDEX IF NOT EXISTS gym_slots_time_idx ON gym_slots(start_time);
CREATE INDEX IF NOT EXISTS gym_slots_gym_time_idx ON gym_slots(gym_id, start_time);
CREATE INDEX IF NOT EXISTS bookings_user_slot_active_idx
  ON bookings(user_id, slot_id)
  WHERE slot_id IS NOT NULL AND status = 'upcoming';
CREATE INDEX IF NOT EXISTS bookings_user_booking_date_idx ON bookings(user_id, booking_date DESC);
CREATE INDEX IF NOT EXISTS bookings_user_status_idx ON bookings(user_id, status);
CREATE INDEX IF NOT EXISTS user_subscriptions_user_expiry_idx ON user_subscriptions(user_id, expiry_date DESC);
CREATE INDEX IF NOT EXISTS hydration_goals_user_id_idx ON hydration_goals(user_id);
CREATE INDEX IF NOT EXISTS hydration_daily_user_id_idx ON hydration_daily(user_id);
CREATE INDEX IF NOT EXISTS hydration_daily_date_idx ON hydration_daily(date);
CREATE INDEX IF NOT EXISTS step_tracker_goals_user_id_idx ON step_tracker_goals(user_id);
CREATE INDEX IF NOT EXISTS step_tracker_daily_user_id_idx ON step_tracker_daily(user_id);
CREATE INDEX IF NOT EXISTS step_tracker_daily_date_idx ON step_tracker_daily(date);
CREATE INDEX IF NOT EXISTS step_tracker_daily_updated_at_idx ON step_tracker_daily(updated_at);
CREATE INDEX IF NOT EXISTS posts_user_id_idx ON posts(user_id);
CREATE INDEX IF NOT EXISTS post_comments_post_id_idx ON post_comments(post_id);
CREATE INDEX IF NOT EXISTS post_likes_post_id_idx ON post_likes(post_id);
CREATE INDEX IF NOT EXISTS post_favourites_post_id_idx ON post_favourites(post_id);
CREATE INDEX IF NOT EXISTS user_followers_follower_id_idx ON user_followers(follower_id);
CREATE INDEX IF NOT EXISTS user_followers_following_id_idx ON user_followers(following_id);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email)
  VALUES (new.id, new.email);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_user_subscriptions_updated_at ON user_subscriptions;
CREATE TRIGGER set_user_subscriptions_updated_at
BEFORE UPDATE ON user_subscriptions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS set_gyms_updated_at ON gyms;
CREATE TRIGGER set_gyms_updated_at
BEFORE UPDATE ON gyms
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS set_package_gyms_updated_at ON package_gyms;
CREATE TRIGGER set_package_gyms_updated_at
BEFORE UPDATE ON package_gyms
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS set_gym_slots_updated_at ON gym_slots;
CREATE TRIGGER set_gym_slots_updated_at
BEFORE UPDATE ON gym_slots
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP FUNCTION IF EXISTS get_user_credit_balance(UUID, UUID);
CREATE OR REPLACE FUNCTION get_user_credit_balance(
  p_user_id UUID,
  p_package_id UUID DEFAULT NULL
)
RETURNS JSONB
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT
    CASE
      WHEN auth.uid() IS NULL OR auth.uid() <> p_user_id THEN
        jsonb_build_object('success', false, 'error', 'unauthorized')
      WHEN p_package_id IS NULL THEN
        COALESCE(
          (
            SELECT jsonb_build_object(
              'success', true,
              'sessions_remaining', COALESCE(SUM(sessions_remaining), 0),
              'active_subscriptions', COUNT(*) FILTER (WHERE expiry_date >= CURRENT_DATE),
              'next_expiry_date', MIN(expiry_date) FILTER (WHERE expiry_date >= CURRENT_DATE)
            )
            FROM user_subscriptions
            WHERE user_id = p_user_id
              AND expiry_date >= CURRENT_DATE
          ),
          jsonb_build_object(
            'success', true,
            'sessions_remaining', 0,
            'active_subscriptions', 0,
            'next_expiry_date', NULL
          )
        )
      ELSE
        COALESCE(
          (
            SELECT jsonb_build_object(
              'success', true,
              'sessions_remaining', COALESCE(SUM(sessions_remaining), 0),
              'active_subscriptions', COUNT(*) FILTER (WHERE expiry_date >= CURRENT_DATE),
              'next_expiry_date', MIN(expiry_date) FILTER (WHERE expiry_date >= CURRENT_DATE)
            )
            FROM user_subscriptions
            WHERE user_id = p_user_id
              AND package_id = p_package_id
              AND expiry_date >= CURRENT_DATE
          ),
          jsonb_build_object(
            'success', true,
            'sessions_remaining', 0,
            'active_subscriptions', 0,
            'next_expiry_date', NULL
          )
        )
    END;
$$;

DROP FUNCTION IF EXISTS create_booking_with_credit(UUID, UUID, UUID);
CREATE OR REPLACE FUNCTION create_booking_with_credit(
  p_user_id UUID,
  p_slot_id UUID,
  p_package_id UUID
)
RETURNS JSONB
LANGUAGE sql
SECURITY DEFINER
AS $$
  WITH auth_check AS (
    SELECT auth.uid() IS NOT NULL AND auth.uid() = p_user_id AS ok
  ),
  subscription AS (
    SELECT us.id, us.package_id, p.allowed_class_names
    FROM user_subscriptions us
    JOIN packages p ON p.id = us.package_id
    WHERE us.user_id = p_user_id
      AND us.package_id = p_package_id
      AND us.expiry_date >= CURRENT_DATE
      AND us.sessions_remaining > 0
    ORDER BY us.expiry_date DESC
    LIMIT 1
    FOR UPDATE
  ),
  slot_state AS (
    SELECT gs.id, gs.gym_id, gs.start_time, gs.total_spots, gs.occupied_spots, gs.class_name
    FROM gym_slots gs
    WHERE gs.id = p_slot_id
      AND gs.start_time > now()
    FOR UPDATE
  ),
  duplicate_booking AS (
    SELECT 1
    FROM bookings b
    WHERE b.user_id = p_user_id
      AND b.slot_id = p_slot_id
      AND b.status = 'upcoming'
    LIMIT 1
  ),
  inserted AS (
    INSERT INTO bookings (
      user_id,
      package_id,
      slot_id,
      status,
      booking_date,
      total_paid,
      session_number,
      qr_code_data
    )
    SELECT
      p_user_id,
      p_package_id,
      p_slot_id,
      'upcoming',
      (SELECT start_time FROM slot_state),
      0,
      1,
      'QR-' || gen_random_uuid()::text
    FROM auth_check a
    WHERE a.ok
      AND EXISTS (SELECT 1 FROM subscription)
      AND EXISTS (SELECT 1 FROM slot_state WHERE occupied_spots < total_spots)
      AND EXISTS (
        SELECT 1
        FROM subscription s
        JOIN slot_state ss ON TRUE
        JOIN package_gyms pg
          ON pg.package_id = s.package_id
         AND pg.gym_id = ss.gym_id
         AND pg.is_active = TRUE
      )
      AND EXISTS (
        SELECT 1
        FROM subscription s
        JOIN slot_state ss ON TRUE
        WHERE COALESCE(array_length(s.allowed_class_names, 1), 0) = 0
           OR ss.class_name = ANY(s.allowed_class_names)
      )
      AND NOT EXISTS (SELECT 1 FROM duplicate_booking)
    RETURNING id
  ),
  decremented_subscription AS (
    UPDATE user_subscriptions us
    SET sessions_remaining = us.sessions_remaining - 1
    WHERE us.id = (SELECT id FROM subscription)
      AND EXISTS (SELECT 1 FROM inserted)
    RETURNING 1
  ),
  incremented_slot AS (
    UPDATE gym_slots gs
    SET occupied_spots = gs.occupied_spots + 1
    WHERE gs.id = p_slot_id
      AND EXISTS (SELECT 1 FROM inserted)
    RETURNING 1
  ),
  updated_booking AS (
    UPDATE bookings b
    SET qr_code_data = jsonb_build_object(
      'booking_id', b.id,
      'user_id', p_user_id,
      'slot_id', p_slot_id,
      'package_id', p_package_id
    )::TEXT
    FROM inserted i
    WHERE b.id = i.id
    RETURNING b.*
  )
  SELECT CASE
    WHEN NOT EXISTS (SELECT 1 FROM auth_check WHERE ok) THEN
      jsonb_build_object('success', false, 'error', 'unauthorized')
    WHEN NOT EXISTS (SELECT 1 FROM subscription) THEN
      jsonb_build_object('success', false, 'error', 'No sessions remaining. Please purchase a package.')
    WHEN NOT EXISTS (SELECT 1 FROM slot_state) THEN
      jsonb_build_object('success', false, 'error', 'Selected slot not found.')
    WHEN EXISTS (SELECT 1 FROM slot_state WHERE occupied_spots >= total_spots) THEN
      jsonb_build_object('success', false, 'error', 'Selected slot is already full.')
    WHEN EXISTS (
      SELECT 1
      FROM subscription s
      JOIN slot_state ss ON TRUE
      WHERE COALESCE(array_length(s.allowed_class_names, 1), 0) > 0
        AND ss.class_name <> ALL(s.allowed_class_names)
    ) THEN
      jsonb_build_object('success', false, 'error', 'This slot is not available for the selected package.')
    WHEN NOT EXISTS (
      SELECT 1
      FROM subscription s
      JOIN slot_state ss ON TRUE
      JOIN package_gyms pg
        ON pg.package_id = s.package_id
       AND pg.gym_id = ss.gym_id
       AND pg.is_active = TRUE
    ) THEN
      jsonb_build_object('success', false, 'error', 'This package is not available for the selected gym.')
    WHEN EXISTS (SELECT 1 FROM duplicate_booking) THEN
      jsonb_build_object('success', false, 'error', 'You already booked this slot.')
    WHEN NOT EXISTS (SELECT 1 FROM inserted) THEN
      jsonb_build_object('success', false, 'error', 'Unable to create booking.')
    ELSE
      jsonb_build_object('success', true, 'booking', (SELECT to_jsonb(ub) FROM updated_booking ub LIMIT 1))
  END;
$$;

DROP FUNCTION IF EXISTS cancel_booking_with_refund(UUID, UUID);
CREATE OR REPLACE FUNCTION cancel_booking_with_refund(
  p_booking_id UUID,
  p_user_id UUID
)
RETURNS JSONB
LANGUAGE sql
SECURITY DEFINER
AS $$
  WITH auth_check AS (
    SELECT auth.uid() IS NOT NULL AND auth.uid() = p_user_id AS ok
  ),
  booking_row AS (
    SELECT b.id, b.package_id, b.slot_id, b.status
    FROM bookings b
    WHERE b.id = p_booking_id
      AND b.user_id = p_user_id
    FOR UPDATE
  ),
  updated_booking AS (
    UPDATE bookings b
    SET status = 'missed'
    WHERE b.id = p_booking_id
      AND EXISTS (SELECT 1 FROM auth_check WHERE ok)
      AND EXISTS (SELECT 1 FROM booking_row WHERE status = 'upcoming')
    RETURNING 1
  ),
  updated_subscription AS (
    UPDATE user_subscriptions us
    SET sessions_remaining = us.sessions_remaining + 1
    WHERE us.id = (
      SELECT us2.id
      FROM user_subscriptions us2
      WHERE us2.user_id = p_user_id
        AND us2.package_id = (SELECT br.package_id FROM booking_row br LIMIT 1)
      ORDER BY us2.expiry_date DESC
      LIMIT 1
    )
      AND EXISTS (SELECT 1 FROM updated_booking)
    RETURNING 1
  ),
  updated_slot AS (
    UPDATE gym_slots gs
    SET occupied_spots = GREATEST(gs.occupied_spots - 1, 0)
    WHERE gs.id = (SELECT br.slot_id FROM booking_row br LIMIT 1)
      AND (SELECT br.slot_id FROM booking_row br LIMIT 1) IS NOT NULL
      AND EXISTS (SELECT 1 FROM updated_booking)
    RETURNING 1
  )
  SELECT CASE
    WHEN NOT EXISTS (SELECT 1 FROM auth_check WHERE ok) THEN
      jsonb_build_object('success', false, 'error', 'unauthorized')
    WHEN NOT EXISTS (SELECT 1 FROM booking_row) THEN
      jsonb_build_object('success', false, 'error', 'Booking not found.')
    WHEN EXISTS (SELECT 1 FROM booking_row WHERE status <> 'upcoming') THEN
      jsonb_build_object('success', false, 'error', 'Only upcoming bookings can be cancelled.')
    WHEN NOT EXISTS (SELECT 1 FROM updated_booking) THEN
      jsonb_build_object('success', false, 'error', 'Unable to cancel booking.')
    ELSE
      jsonb_build_object('success', true)
  END;
$$;

DROP FUNCTION IF EXISTS reschedule_booking(UUID, UUID, UUID);
CREATE OR REPLACE FUNCTION reschedule_booking(
  p_booking_id UUID,
  p_user_id UUID,
  p_new_slot_id UUID
)
RETURNS JSONB
LANGUAGE sql
SECURITY DEFINER
AS $$
  WITH auth_check AS (
    SELECT auth.uid() IS NOT NULL AND auth.uid() = p_user_id AS ok
  ),
  booking_row AS (
    SELECT b.id, b.package_id, b.slot_id, b.status
    FROM bookings b
    WHERE b.id = p_booking_id
      AND b.user_id = p_user_id
    FOR UPDATE
  ),
  new_slot AS (
    SELECT gs.id, gs.gym_id, gs.total_spots, gs.occupied_spots, gs.class_name
    FROM gym_slots gs
    WHERE gs.id = p_new_slot_id
    FOR UPDATE
  ),
  updated_booking AS (
    UPDATE bookings b
    SET slot_id = p_new_slot_id
    WHERE b.id = p_booking_id
      AND EXISTS (SELECT 1 FROM auth_check WHERE ok)
      AND EXISTS (SELECT 1 FROM booking_row WHERE status = 'upcoming')
      AND EXISTS (SELECT 1 FROM new_slot WHERE occupied_spots < total_spots)
      AND EXISTS (
        SELECT 1
        FROM booking_row br
        JOIN packages p ON p.id = br.package_id
        JOIN new_slot ns ON TRUE
        JOIN package_gyms pg
          ON pg.package_id = br.package_id
         AND pg.gym_id = ns.gym_id
         AND pg.is_active = TRUE
        WHERE COALESCE(array_length(p.allowed_class_names, 1), 0) = 0
           OR ns.class_name = ANY(p.allowed_class_names)
      )
      AND EXISTS (SELECT 1 FROM booking_row WHERE slot_id IS DISTINCT FROM p_new_slot_id)
    RETURNING 1
  ),
  old_slot_update AS (
    UPDATE gym_slots gs
    SET occupied_spots = GREATEST(gs.occupied_spots - 1, 0)
    WHERE gs.id = (SELECT br.slot_id FROM booking_row br LIMIT 1)
      AND EXISTS (SELECT 1 FROM updated_booking)
      AND (SELECT br.slot_id FROM booking_row br LIMIT 1) IS NOT NULL
    RETURNING 1
  ),
  new_slot_update AS (
    UPDATE gym_slots gs
    SET occupied_spots = gs.occupied_spots + 1
    WHERE gs.id = p_new_slot_id
      AND EXISTS (SELECT 1 FROM updated_booking)
    RETURNING 1
  )
  SELECT CASE
    WHEN NOT EXISTS (SELECT 1 FROM auth_check WHERE ok) THEN
      jsonb_build_object('success', false, 'error', 'unauthorized')
    WHEN NOT EXISTS (SELECT 1 FROM booking_row) THEN
      jsonb_build_object('success', false, 'error', 'Booking not found.')
    WHEN EXISTS (SELECT 1 FROM booking_row WHERE status <> 'upcoming') THEN
      jsonb_build_object('success', false, 'error', 'Only upcoming bookings can be rescheduled.')
    WHEN EXISTS (SELECT 1 FROM booking_row WHERE slot_id = p_new_slot_id) THEN
      jsonb_build_object('success', false, 'error', 'Please choose a different slot.')
    WHEN NOT EXISTS (SELECT 1 FROM new_slot) THEN
      jsonb_build_object('success', false, 'error', 'New slot not found.')
    WHEN EXISTS (SELECT 1 FROM new_slot WHERE occupied_spots >= total_spots) THEN
      jsonb_build_object('success', false, 'error', 'New slot is already full.')
    WHEN NOT EXISTS (
      SELECT 1
      FROM booking_row br
      JOIN package_gyms pg ON pg.package_id = br.package_id AND pg.is_active = TRUE
      JOIN new_slot ns ON ns.gym_id = pg.gym_id
    ) THEN
      jsonb_build_object('success', false, 'error', 'This package is not available for the selected gym.')
    WHEN NOT EXISTS (SELECT 1 FROM updated_booking) THEN
      jsonb_build_object('success', false, 'error', 'Unable to reschedule booking.')
    ELSE
      jsonb_build_object('success', true)
  END;
$$;

GRANT EXECUTE ON FUNCTION get_user_credit_balance(UUID, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION create_booking_with_credit(UUID, UUID, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION cancel_booking_with_refund(UUID, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION reschedule_booking(UUID, UUID, UUID) TO authenticated;
GRANT SELECT ON packages TO authenticated;
GRANT SELECT ON gyms TO authenticated;
GRANT SELECT ON package_gyms TO authenticated;
GRANT SELECT ON gym_slots TO authenticated;
GRANT ALL ON stripe_webhook_events TO service_role;

INSERT INTO storage.buckets (id, name, public, allowed_mime_types)
VALUES (
  'community_media',
  'community_media',
  true,
  ARRAY['image/*', 'video/*']::text[]
)
ON CONFLICT (id) DO UPDATE
SET allowed_mime_types = ARRAY['image/*', 'video/*']::text[];

DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" ON storage.objects
FOR SELECT USING (bucket_id = 'community_media');

DROP POLICY IF EXISTS "Auth Insert" ON storage.objects;
CREATE POLICY "Auth Insert" ON storage.objects
FOR INSERT WITH CHECK (
  bucket_id = 'community_media'
  AND auth.role() = 'authenticated'
);

DROP POLICY IF EXISTS "Auth Delete" ON storage.objects;
CREATE POLICY "Auth Delete" ON storage.objects
FOR DELETE USING (
  bucket_id = 'community_media'
  AND auth.uid()::text = (string_to_array(name, '/'))[1]
);

-- Avatar storage bucket + policies
INSERT INTO storage.buckets (id, name, public, allowed_mime_types)
VALUES (
  'avatars',
  'avatars',
  true,
  ARRAY['image/*']::text[]
)
ON CONFLICT (id) DO UPDATE
SET public = true,
    allowed_mime_types = ARRAY['image/*']::text[];

DROP POLICY IF EXISTS "Avatar public read" ON storage.objects;
CREATE POLICY "Avatar public read" ON storage.objects
FOR SELECT
TO public
USING (bucket_id = 'avatars');

DROP POLICY IF EXISTS "Avatar upload own folder" ON storage.objects;
CREATE POLICY "Avatar upload own folder" ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'avatars'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

DROP POLICY IF EXISTS "Avatar update own folder" ON storage.objects;
CREATE POLICY "Avatar update own folder" ON storage.objects
FOR UPDATE
TO authenticated
USING (
  bucket_id = 'avatars'
  AND (storage.foldername(name))[1] = auth.uid()::text
)
WITH CHECK (
  bucket_id = 'avatars'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

DROP POLICY IF EXISTS "Avatar delete own folder" ON storage.objects;
CREATE POLICY "Avatar delete own folder" ON storage.objects
FOR DELETE
TO authenticated
USING (
  bucket_id = 'avatars'
  AND (storage.foldername(name))[1] = auth.uid()::text
);


